name: Crawl

on:
  push:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: gh-pages

    - run: pip3 install urllib3

    - run: "curl -LO 'https://github.com/imba-tjd/dlwatcher/raw/master/{data_tmpl.html,dlwatcher.py,deploy.sh}' -H 'Cache-Control: no-cache'"

    - run: |
        python3 dlwatcher.py
        mv data.html index.html

    - run: bash deploy.sh
