on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: gh_pages

    - run: |
        curl -fL https://github.com/imba-tjd/dlwatcher/raw/master/dlwatcher.py | python -c
        mv data.html index.html

        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "GitHub Actions"
        git add .
        git commit -m "Update"
        git push
