name: Crawl

on:
  push:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: gh_pages

    - uses: actions/setup-python@v3
    - run: pip3 install urllib3

    - run: |
        curl -LO https://github.com/imba-tjd/dlwatcher/raw/master/data_tmpl.html

        curl -fL https://github.com/imba-tjd/dlwatcher/raw/master/dlwatcher.py | python3
        mv data.html index.html

        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "GitHub Actions"
        git add data.csv index.html
        git commit -m "Update"
        git push
